# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Costmeter < Formula
  desc "Cost tracking & budget enforcement for AI agent API calls"
  homepage "https://costmeter.io"
  version "2.2.0-alpha"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ggonzalezaleman/costmeter/releases/download/v2.2.0-alpha/costmeter_2.2.0-alpha_darwin_amd64.tar.gz"
      sha256 "4b9d325e54566607d32cd734885044cd2f000b8030a5c04583b9cf51aeea4d33"

      define_method(:install) do
        bin.install "costmeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ggonzalezaleman/costmeter/releases/download/v2.2.0-alpha/costmeter_2.2.0-alpha_darwin_arm64.tar.gz"
      sha256 "431dc0356b826e9b3ea215910f7bd17119e26e58c1033072674b6c59f8f0d3ab"

      define_method(:install) do
        bin.install "costmeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggonzalezaleman/costmeter/releases/download/v2.2.0-alpha/costmeter_2.2.0-alpha_linux_amd64.tar.gz"
      sha256 "ddfdde2f45d6e3709315dedba95b44a7d253c99672c3cf2e623a5f79beba0e0d"
      define_method(:install) do
        bin.install "costmeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggonzalezaleman/costmeter/releases/download/v2.2.0-alpha/costmeter_2.2.0-alpha_linux_arm64.tar.gz"
      sha256 "e642f9218b9000c969c0667efda995343f73e10e1005cece7d91146c1f63d3df"
      define_method(:install) do
        bin.install "costmeter"
      end
    end
  end
end
